---
- hosts: 'localhost'
  gather_facts: no
  vars_files:
    - ../vars.yml
  tasks:
    - include_tasks: azure-env-res-creation.yml
    - include_tasks: azure-db-res-creation.yml
      when: local_db=='no'
    - include_tasks: azure-ws-res-creation.yml
    - include_tasks: azure-waap-res-creation.yml
    - include_tasks: azure-elk-res-creation.yml
    - meta: refresh_inventory
# dynamic inventory
# DB server deployment
- hosts: Type_dbsvr
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  strategy: free
  vars_files:
    - ../vars.yml
  tasks:
    - include_tasks: ../hackazon-dbsvr.yml
      when: local_db=='no'


- hosts: Enum_websvr1
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  strategy: free
  vars_files:
   - ../vars.yml
  tasks:
  - include_tasks: ../hackazon-dbsvr.yml
    when: local_db=='yes'


#Web Servers Deployment
- hosts: Type_websvr
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  strategy: free
  vars_files:
    - ../vars.yml
  tasks:
    - set_fact: #override vars_files variables only for Azure deployment.
        mysql_host: "{{ hostvars['localhost']['mysql_host'] }}"
      when: local_db=='no'
    - debug: var=mysql_host
    - include_tasks: ../hackazon-websvr.yml

- hosts: Type_elksvr
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  strategy: free
  vars_files:
    - ../vars.yml
  tasks:
  - include_tasks: ../hackazon-elksvr.yml

- hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: no
  vars_files:
    - ../vars.yml
  environment:
    F5_USER: '{{ admin_username }}'
    F5_PASSWORD: '{{ admin_password }}'
    F5_SERVER:  "{{ hostvars['localhost']['f5_host']}}"
    F5_SERVER_PORT: '8443'
    F5_VALIDATE_CERTS: 'no'
  tasks:
   - set_fact: #override vars_files elk variables only for Azure deployment.
       ws_host: "{{ hostvars['localhost']['ws_host'] }}"
       elk_host: "{{ hostvars['localhost']['elk_host'] }}"
   - include_tasks: ../hackazon-f5waap.yml
   - debug:
        msg:
          - "Playbook is complete"
          - "Please add {{ server_name }} {{ hostvars['localhost']['f5_host']}} to your hostfile/DNS"
          - "Hackazon App: https://{{ server_name }}"
          - "F5 WAAP GUI: https://{{ server_name }}:8443"
          - "Kibana GUI: https://{{ server_name }}:5601"
