--- #deploy web server 
- hosts: dbservers
  remote_user: ansible
  become: yes 
  become_method: sudo
  connection: ssh 
  gather_facts: no
  vars_files:
   - vars.yml
  tasks:
   #- debug: var=mysql_password
  - name: set mysql passwd 
    debconf: 
      name: 'mysql-server'
      question: 'mysql-server/root_password'
      value: '{{ mysql_password | quote }}'
      vtype: 'password'
  - name: confirm mysql passwd
    debconf:
      name: 'mysql-server'
      question: 'mysql-server/root_password_again'
      value: '{{ mysql_password | quote }}'
      vtype: 'password'
  - name: install mysql packages
    apt: 
      name: "{{ item }}"
      update_cache: yes
      state: present
      force: yes
    with_items:
      - mysql-server
      - mysql-client
      - python-mysqldb 
    notify: 
      - service_handler
  - name: crate hackazon db
    mysql_db: 
      name: hackazon
      state: present
      login_user: root
      login_password: '{{ mysql_password | quote }}' 
  - name: create hackazon user and grant access to hackazon db
    mysql_user:
      name: hackazon
      password: '{{ mysql_password | quote }}'
      priv: "hackazon.*:ALL"
      login_user: root
      login_password: '{{ mysql_password | quote }}'
      state: present
  handlers:
  - name: service_handler 
    service:
      name: mysql
      enabled: yes 
      state: restarted  
