--- #deploy web server 
- hosts: webservers
  remote_user: ansible
  become: yes 
  become_method: sudo
  connection: ssh 
  gather_facts: no
  vars_files:
   - vars.yml 
  tasks:
  - name: add php 5.6 repository 
    apt_repository:
      repo: 'ppa:ondrej/php'
  - name: install packages
    apt: 
      name: "{{ item }}"
      update_cache: yes
      state: present
    with_items:
      - software-properties-common
      - apache2 
      - php5.6
      - php5.6-mysql
      - php5.6-xml
      - php5.6-bcmath
      - php5.6-mbstring 
      - libapache2-mod-php5.6
    notify: 
    - service_handler
  - name: install supporting bins 
    apt: 
      name: "{{ item }}"
      state: present
    with_items:
      - git-all
      - wget
  - name: enable rewrite module
    apache2_module:
      state: present
      name: rewrite

  - name: clone hackazon from git
    git: 
      repo: 'https://github.com/ianwijaya/hackazon'
      dest: /var/www/hackazon
      force: yes
      recursive: no
  - name: download Hackazon virtual host configuration
    get_url: 
      url: 'https://raw.githubusercontent.com/ianwijaya/hackazon-iac/master/config/010-hackazon.conf'
      dest: /etc/apache2/sites-available/010-hackazon.conf
  - name: create symlink of virtual host configuration
    file: src=/etc/apache2/sites-available/010-hackazon.conf  dest=/etc/apache2/sites-enabled/010-hackazon.conf state=link 
  - name: change owner of hackazon directory 
    command: "chown -R www-data:www-data /var/www/hackazon"
    changed_when: false 
  - name: run php composer 
    shell: 'php composer.phar install -o --prefer-dist'
    args: 
      chdir: '/var/www/hackazon'
  - name: add db connection configuration (db.php)
    template: 
      src: templates/db.php.j2
      dest: /var/www/hackazon/assets/config/db.php 
      owner: www-data
      group: www-data
  handlers:
  - name: service_handler 
    service:
      name: apache2
      enabled: yes 
      state: restarted	  
