---
# dbservers deployment
# don't forget to change your /etc/ansible/host 
- hosts: dbservers
  remote_user: ansible
  become: yes 
  become_method: sudo
  connection: ssh
  gather_facts: no 
  vars_files:
    - vars.yml 
  tasks: 
    - include_tasks: hackazon-dbsvr.yml

#Web Servers Deployment
- hosts: webservers
  remote_user: ansible 
  become: yes
  become_method: sudo
  connection: ssh 
  gather_facts: no
  vars_files: 
    - vars.yml 
  tasks: 
    - include_tasks: hackazon-websvr.yml


